## Preprocessing

In [74]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [76]:
application_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [78]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [10]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values.head()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
dtype: int64

In [12]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type = application_df['APPLICATION_TYPE'].value_counts()
application_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [16]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = application_type[application_type < cutoff_value].index.tolist()


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [18]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_count = application_df ['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count_1 = classification_count[classification_count >1]
classification_count_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1883
classifications_to_replace = classification_count[classification_count < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [26]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [82]:
# Count the frequency of each unique name
name_counts = application_df['NAME'].value_counts()

# Define a cutoff value for grouping rare names
cutoff_value = 5
names_to_replace = name_counts[name_counts <= cutoff_value].index.tolist()

# Replace rare names with "Other"
application_df['NAME'] = application_df['NAME'].replace(names_to_replace, "Other")

# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [83]:
application_df.columns

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'NAME_AACE INTERNATIONAL',
       'NAME_ACE MENTOR PROGRAM OF AMERICA INC',
       'NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS',
       'NAME_AIR FORCE ASSOCIATION', 'NAME_ALABAMA FEDERATION OF WOMENS CLUBS',
       'NAME_ALABAMA TREASURE FOREST ASSOCIATION',
       'NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION',
       ...
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'],
      dtype='object', length=472)

In [84]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=['IS_SUCCESSFUL'])
y = application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=78)

In [85]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [87]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]
hidden_nodes_layer1 =  128
hidden_nodes_layer2 = 64

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 128)            │        60,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 68,737 (268.50 KB)

 Trainable params: 68,737 (268.50 KB)

 Non-trainable params: 0 (0.00 B)

In [88]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [89]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.7564 - loss: 0.5033
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.7938 - loss: 0.4283
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.7911 - loss: 0.4306
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.8019 - loss: 0.4133
Epoch 5/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.8010 - loss: 0.4180
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8000 - loss: 0.4205
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - accuracy: 0.8012 - loss: 0.4166
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7984 - loss: 0.4168
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.8039 - loss: 0.4142
Epoch 10/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.8074 - loss: 0.4091
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.8016 - loss: 0.4162
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - accuracy: 0.8022 - loss: 0.4145
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.8009 - loss: 0.4147
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - accuracy: 0.7985 - loss: 0.4163
Epoch 15/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 787us/step - accuracy: 0.7989 - loss: 0.4166
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.8038 - loss: 0.4147
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 714us/step - accuracy: 0.8061 - loss: 0.4080
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 771us/step - accuracy: 0.8067 - loss: 0.4072
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.8064 - loss: 0.4084
Epoch 20/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 705us/step - accuracy: 0.8075 - loss: 0.4072
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 686us/step - accuracy: 0.8059 - loss: 0.4042
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.8054 - loss: 0.4063
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 698us/step - accuracy: 0.8055 - loss: 0.4076
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 694us/step - accuracy: 0.8034 - loss: 0.4112
Epoch 25/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 735us/step - accuracy: 0.8054 - loss: 0.4058
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - accuracy: 0.8085 - loss: 0.4028
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 686us/step - accuracy: 0.8031 - loss: 0.4111
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.8081 - loss: 0.4004
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 813us/step - accuracy: 0.8067 - loss: 0.4081
Epoch 30/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - accuracy: 0.8037 - loss: 0.4110
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 795us/step - accuracy: 0.8065 - loss: 0.4041
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - accuracy: 0.8072 - loss: 0.4069
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 802us/step - accuracy: 0.8084 - loss: 0.4032
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.8094 - loss: 0.4009
Epoch 35/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 737us/step - accuracy: 0.8055 - loss: 0.4055
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.8034 - loss: 0.4070
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 726us/step - accuracy: 0.8078 - loss: 0.4012
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.8078 - loss: 0.4073
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.8082 - loss: 0.4039
Epoch 40/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8104 - loss: 0.3979
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.8072 - loss: 0.4050
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.8082 - loss: 0.4013
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.8053 - loss: 0.4070
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 735us/step - accuracy: 0.8098 - loss: 0.4001
Epoch 45/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.8110 - loss: 0.3976
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 790us/step - accuracy: 0.8075 - loss: 0.4019
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.8135 - loss: 0.3979
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.8108 - loss: 0.3999
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.8130 - loss: 0.3992
Epoch 50/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.8046 - loss: 0.4038
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.8111 - loss: 0.3934
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.8104 - loss: 0.3969
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.8125 - loss: 0.3983
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 737us/step - accuracy: 0.8077 - loss: 0.4051
Epoch 55/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.8078 - loss: 0.4027
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.8102 - loss: 0.4001
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.8042 - loss: 0.4063
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.8071 - loss: 0.4013
Epoch 59/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.8118 - loss: 0.3970
Epoch 60/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.8042 - loss: 0.4023
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 797us/step - accuracy: 0.8118 - loss: 0.3978
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.8104 - loss: 0.3946
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.8090 - loss: 0.3991
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.8109 - loss: 0.3962
Epoch 65/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.8073 - loss: 0.4020
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.8138 - loss: 0.3956
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.8117 - loss: 0.3953
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.8086 - loss: 0.4018
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.8075 - loss: 0.4020
Epoch 70/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.8127 - loss: 0.3940
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.8129 - loss: 0.3944
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.8117 - loss: 0.3982
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.8141 - loss: 0.3965
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 747us/step - accuracy: 0.8106 - loss: 0.3994
Epoch 75/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.8104 - loss: 0.3956
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 746us/step - accuracy: 0.8127 - loss: 0.3925
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 823us/step - accuracy: 0.8078 - loss: 0.3992
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.8108 - loss: 0.3974
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.8112 - loss: 0.3940
Epoch 80/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.8089 - loss: 0.3968
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.8094 - loss: 0.3944
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 708us/step - accuracy: 0.8119 - loss: 0.3954
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.8137 - loss: 0.3959
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.8125 - loss: 0.3904
Epoch 85/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.8098 - loss: 0.3951
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.8076 - loss: 0.3975
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.8073 - loss: 0.3994
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 734us/step - accuracy: 0.8108 - loss: 0.3970
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.8098 - loss: 0.3954
Epoch 90/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.8115 - loss: 0.3963
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 754us/step - accuracy: 0.8134 - loss: 0.3925
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.8132 - loss: 0.3920
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.8107 - loss: 0.3966
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.8148 - loss: 0.3931
Epoch 95/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 734us/step - accuracy: 0.8131 - loss: 0.3944
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.8098 - loss: 0.3953
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.8049 - loss: 0.4037
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - accuracy: 0.8137 - loss: 0.3919
Epoch 99/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.8139 - loss: 0.3920
Epoch 100/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - accuracy: 0.8054 - loss: 0.4008

In [97]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 940us/step - accuracy: 0.7870 - loss: 0.5022
Loss: 0.5022066831588745, Accuracy: 0.7870262265205383

In [101]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.